version: '3.1'

services:
  mysql:
    image: 'mysql:5.7'
    container_name: source-mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'four_seas'
      TZ: 'UTC'
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
  app:
    container_name: source-app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/www
    command:
      - 'sh'
      - '-c'
      - 'scrapy crawl beike'
